version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"  # RabbitMQ main port
      - "15672:15672"  # RabbitMQ management plugin port
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit frame_max 131072"

  web_server:
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./applications/basic_server/src/main/start:/project/app 
    ports:
      - "5000:5000"  
    working_dir: /project
    command: ["./wait-for-it.sh", "-t", "1000", "rabbitmq:5672", "--", "python", "applications/basic_server/src/main/start/App.py"]  # Specify the wait time for app wait for rabbit
    environment:
      RABBITMQ_HOST: "rabbitmq"

  data_collector:
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./applications/data_collector_server/src/main/start:/project/app
    ports:
      - "5001:80" #probably the wrong internal port, but irrelevant
    working_dir: /project
    command: ["./wait-for-it.sh", "-t", "1000", "rabbitmq:5672", "--", "python", "applications/data_collector_server/src/main/start/App.py"]
    environment:
      RABBITMQ_HOST: "rabbitmq"

  data_analyzer:
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./applications/data_analyzer_server/src/main/start:/project/app
    ports:
      - "5002:80" #probably the wrong internal port, but irrelevant
    working_dir: /project
    command: ["./wait-for-it.sh", "-t", "1000", "rabbitmq:5672", "--", "python", "applications/data_analyzer_server/src/main/start/App.py"]
    environment:
      RABBITMQ_HOST: "rabbitmq"
