name: Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    
    - name: Run unit tests for basic_server
      run: |
        python -m unittest discover applications/basic_server/src/test/

    - name: Run unit tests for data_collector
      run: |
        python -m unittest discover applications/data_collector_server/src/test/

    - name: Run unit tests for data_analyzer
      run: |
        python -m unittest discover applications/data_analyzer_server/src/test/